name: deploy-dockerize-run

on: 
  push:
      branches:
        - master


jobs:
  prod-install-deps:
    if: contains(github.event.head_commit.message, 'prod-install-deps')
    runs-on: ubuntu-22.04
    name: 'prod install dependencies'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: Dockerfile.npm
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REGISTRY }}/unimun/unimun-landings-npm-prod:latest
            
      - name: send err log
        if: failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://log.m3m.dev/api/unimun-admin-deploy.php?type=PROD&token=61875b275a6ef7b562b43ce6cc640aaae3cbd1bb6224aab9c3bdb8a45e05ab44'
          method: 'GET'
          
  prod-deploy:
    if: contains(github.event.head_commit.message, 'prod-deploy')
    runs-on: ubuntu-latest
    env:
      FRONT_DEPLOY_PATH: ${{ secrets.ADMIN_PROD_DEPLOY_PATH }}
    name: 'prod deploy'
    steps:
      - name: remove previous files
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.FRONT_DEPLOY_PATH}}
            rm -rf ..?* .[!.]* *
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          
      - uses: actions/checkout@v2
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.ADMIN_PROD_DEPLOY_PATH }}
  
  prod-dockerize-and-run:
    needs: prod-deploy
    if: contains(github.event.head_commit.message, 'prod-deploy')
    runs-on: ubuntu-latest
    name: 'prod dockerize and run'
    env:
      FRONT_DEPLOY_PATH: ${{ secrets.ADMIN_PROD_DEPLOY_PATH }}
    steps:
      - name: run ducker
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.FRONT_DEPLOY_PATH}}
            cd ../
            docker compose up -d --build
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
      - name: send err log
        if: failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://log.m3m.dev/api/unimun-admin-deploy.php?type=PROD&token=61875b275a6ef7b562b43ce6cc640aaae3cbd1bb6224aab9c3bdb8a45e05ab44'
          method: 'GET'
