name: deploy-dockerize-run

on: 
  push:
      branches:
        - main


jobs:
  prod-install-deps:
    if: contains(github.event.head_commit.message, 'prod-install-deps')
    runs-on: ubuntu-22.04
    name: 'prod install dependencies'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: Dockerfile.npm
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REGISTRY }}/unimun/unimun-landings-npm-prod:latest    
      - name: send err log
        if: failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://log.m3m.dev/api/unimun-admin-deploy.php?type=PROD&token=61875b275a6ef7b562b43ce6cc640aaae3cbd1bb6224aab9c3bdb8a45e05ab44'
          method: 'GET'
          
